from enum import Enum


class PromptCode( Enum):
    # Recruitment
    RECRUITMENT_DEFAULT = "RECRUITMENT_REVIEW"

    # Project Tracking
    PROJECT_TRACKING_DEFAULT = "PROJECT_TRACKING_DEFAULT"

    # RAG
    RAG_CHAT = "RAG_CHAT"
    RAG_SUMMARIZATION = "RAG_SUMMARIZATION"

    # Document
    DOCUMENT_SUMMARIZATION = "DOCUMENT_SUMMARIZATION"
    DOCUMENT_TRANSLATION = "DOCUMENT_TRANSLATION"