from enum import Enum


class PromptCode( Enum):
    # Recruitment
    RECRUITMENT_DEFAULT = "RECRUITMENT_REVIEW"
    
    
    REVIEW_DEFAULT = "REVIEW_DEFAULT"

    # Project Tracking
    PROJECT_TRACKING_DEFAULT = "PROJECT_TRACKING_DEFAULT"

    # RAG
    RAG_CHAT = "RAG_CHAT"
    RAG_SUMMARIZATION = "RAG_SUMMARIZATION"

    # Document
    DOCUMENT_SUMMARIZATION = "DOCUMENT_SUMMARIZATION"
    DOCUMENT_TRANSLATION = "DOCUMENT_TRANSLATION"
    
    PUBLIC = "PUBLIC"

    INTERNAL = "INTERNAL"

    COMBINE = "COMBINE"
    
    PROJECT_TRACKING = "PROJECT_TRACKING"
    
    DETECTION = "DETECTION"
    
    PROJECT = "PROJECT"
    
    ALL = "ALL"
    PROJECT_TRACKING_CHAT = "PROJECT_TRACKING_CHAT"
    
    CONTRACT_ANALYZE = "CONTRACT_ANALYZE"
    
    DETECT_CONTRACT = "DETECT_CONTRACT"
    
    CONTRACT_CHAT = "CONTRACT_CHAT"
    
    EXECUTIVE_DATA = "EXECUTIVE_DATA"
    
    EXECUTIVE_DATA_DETECTION = "EXECUTIVE_DATA_DETECTION"
    
    EXECUTIVE_DATA_CHAT = "EXECUTIVE_DATA_CHAT"
    
    HELPDESK = "HELPDESK"
    
    RETRIEVAL_HELPDESK = 10
    
    CHAT_RAG = "CHAT_RAG"
    
    REVIEW_CV = "REVIEW_CV"